export default {
  order: require('./img/order.png'),
  orderActive: require('./img/orderActive.png'),
  customer: require('./img/customer.png'),
  customerActive: require('./img/customerActive.png'),
  own: require('./img/own.png'),
  ownActive: require('./img/ownActive.png'),
  down: require('./img/down.png'),
  address: require('./img/address.png'),
  house: require('./img/house.png'),
  car: require('./img/car.png'),
  baodan: require('./img/baodan.png'),
  card: require('./img/card.png'),
  wld: require('./img/wld.png'),
}